### PR TITLE
rounded corners

### PR DESCRIPTION
**Pull request by Odyssey346**

### CODE REVIEW

**Comment by Devnol** [comment]
1) Please do not commit/pull request directly to the build branch, consider using the dev branch
2) We already have rounded corners in the dev branch

**Comment by Odyssey346** [comment]
Alright, I'll see if there's something I can work on tomorrow. Btw I don't know how to setup a react development environment so don't bother me

**Comment by Devnol** [comment]
Uh... then don't contribute? Or rtfd's

**Comment by Odyssey346** [comment]
Should work fine

**Comment by Midou36O** [comment]
if you want to code get npm and run 'npm install' on the working directory
then run 'npm deploy' to deploy to gh-pages.
shouldn't be hard, especially since you got a good pc unlike mine that has 100% ram all the times.

**Comment by Devnol** [comment]
You don't npm deploy, that literally pushes it to github pages. To test it locally you do npm run.

**Comment by Midou36O** [comment]
> then run 'npm deploy' to **deploy** to **gh-pages**.
and yes i did forget to mention the 'npm run' part but i was outside so couldn't focus :P

**Pull request closed without merging**
