### PR TITLE
add some css and change font

### PR DESCRIPTION
**Pull request by akisblack**
basically have a better font and make background black

### CODE REVIEW

**Comment by Devnol** [comment]
We're not using html for the website so any effort other than minimum effort is not needed. This is just temporary until we get started with react.js

**Comment by akisblack** [comment]
my eyes hurt anyways and there probably won't be an update to this site for 2 months sooooo

**Comment by Midou36O** [comment]
image
you broke it

**Comment by Rexogamer** [comment]
fontastic job

> image
> you broke it

**Comment by Oxygemo** [comment]
What's wrong?

**Comment by Rexogamer** [comment]
*fontastic* job

**Comment by Oxygemo** [comment]
I don't see what's wrong with the font...

**Comment by Midou36O** [comment]
it's not the font, the background is litteraly a black box on a dark box (probably caused by dark reader and this is a big no no in website designing)

**Comment by akisblack** [comment]
~~fuck dark reader, we dont support it~~

**Pull request merged**
