### PR TITLE
rename aaw to ntw in package.json files

### PR DESCRIPTION
**Pull request by Odyssey346**
Signed-off-by: Oxygemo <alej0hio2007@gmail.com>

### CODE REVIEW

**Comment by Devnol** [comment]
LGTM

**Comment by Odyssey346** [comment]
lgtm aswell

**Comment by Devnol** [comment]
Looks good but for the record, you don't edit package-lock directly. You just edit the package and run `npm install`

**Comment by Odyssey346** [comment]
Oh ok.

**Pull request merged**
