### PR TITLE
remove unused file in root

### PR DESCRIPTION
**Pull request by Odyssey346**
Signed-off-by: Oxygemo <alej0hio2007@gmail.com>

### CODE REVIEW

**Comment by Odyssey346** [comment]
This works on my end

**Comment by Odyssey346** [comment]
merge?

**Comment by Odyssey346** [comment]
@Devnol

**Comment by Devnol** [comment]
Uhh, I already did it...

**Comment by Odyssey346** [comment]
couldve merged this one before you did that lol

**Pull request closed without merging**
